// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM7vTX5ern_hkdGpA6md5dCyihGJDCFQg',
    appId: '1:382536456671:web:b0fb9fbf514fae36cb8c6a',
    messagingSenderId: '382536456671',
    projectId: 'alfath-project-2025',
    authDomain: 'alfath-project-2025.firebaseapp.com',
    storageBucket: 'alfath-project-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATmJVpO2jRNZlNdk5KcDNkjKp9JkLH7O8',
    appId: '1:382536456671:android:fde40a22151e62eccb8c6a',
    messagingSenderId: '382536456671',
    projectId: 'alfath-project-2025',
    storageBucket: 'alfath-project-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASLuzJS0Hjp2R54b8j7AvfvudMPE420_I',
    appId: '1:382536456671:ios:f490e31478ba88f1cb8c6a',
    messagingSenderId: '382536456671',
    projectId: 'alfath-project-2025',
    storageBucket: 'alfath-project-2025.firebasestorage.app',
    iosBundleId: 'com.example.miniProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM7vTX5ern_hkdGpA6md5dCyihGJDCFQg',
    appId: '1:382536456671:web:72dda1198a51ec30cb8c6a',
    messagingSenderId: '382536456671',
    projectId: 'alfath-project-2025',
    authDomain: 'alfath-project-2025.firebaseapp.com',
    storageBucket: 'alfath-project-2025.firebasestorage.app',
  );
}
